# The URL the site will be built for
base_url = "https://inputusername.github.io/zola-hook/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Hook"
description = "Hook is a theme for Zola"

taxonomies = [
    { name = "categories" },
    { name = "tags" },
]

[markdown]

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "agola-dark"

bottom_footnotes = true

[extra]
# Put all your custom variables here

links = [
    { title = "Mail", href = "mailto:example@example.com" },
    { title = "GitHub", href = "https://github.com" },
    { title = "LinkedIn", href = "https://linkedin.com" }
]
