name = "Hook"
description = "Clean and simple personal site/blog theme"
license = "MIT"
homepage = "https://github.com/InputUsername/zola-hook"
min_version = "0.19.0"
demo = "https://inputusername.github.io/zola-hook/"

[author]
name = "Koen Bolhuis"
homepage = "https://koen.bolhu.is"
